name: Java CI with Maven

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21 (your project uses Java 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build + run tests
      - name: Build with Maven
        run: mvn -B clean verify

      # Step 4: (Optional) Package the app, skipping tests
      - name: Package application
        run: mvn -B package -DskipTests
